spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  main:
    banner-mode: off

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  jwt:
    issuer: eduDev-test
    secret: edudev-test-secret-key-with-at-least-32-characters
    access-token-expiration: 15m
    refresh-token-expiration: 7d

logging:
  level:
    root: WARN
